function flo_add_stats_box(ax, textValue, x, y)
%FLO_ADD_STATS_BOX Add a small unobtrusive statistics label.
if nargin < 3
    x = 0.03;
end
if nargin < 4
    y = 0.96;
end
text(ax, x, y, textValue, ...
    "Units", "normalized", ...
    "VerticalAlignment", "top", ...
    "HorizontalAlignment", "left", ...
    "FontName", "Helvetica", ...
    "FontSize", 8.5, ...
    "Color", [0.1, 0.1, 0.1], ...
    "BackgroundColor", [1, 1, 1], ...
    "EdgeColor", [0.78, 0.78, 0.78], ...
    "Margin", 6);
end
