function flo_apply_paper_style(ax)
%FLO_APPLY_PAPER_STYLE Minimal style tuned for manuscript figures.
colors = flo_colors();
set(ax, ...
    "FontName", "Helvetica", ...
    "FontSize", 10, ...
    "LineWidth", 0.8, ...
    "Color", "w", ...
    "XColor", colors.dark, ...
    "YColor", colors.dark, ...
    "Box", "off", ...
    "TickDir", "out", ...
    "Layer", "top");
grid(ax, "on");
ax.GridAlpha = 0.14;
ax.GridColor = [0.45, 0.45, 0.45];

ax.Title.Color = colors.dark;
ax.XLabel.Color = colors.dark;
ax.YLabel.Color = colors.dark;
end
