function flo_set_light_theme()
%FLO_SET_LIGHT_THEME Make exported figures independent of MATLAB dark mode.
colors = flo_colors();

set(groot, ...
    "defaultFigureColor", "w", ...
    "defaultAxesColor", "w", ...
    "defaultAxesXColor", colors.dark, ...
    "defaultAxesYColor", colors.dark, ...
    "defaultAxesZColor", colors.dark, ...
    "defaultAxesGridColor", [0.55, 0.55, 0.55], ...
    "defaultTextColor", colors.dark, ...
    "defaultLegendTextColor", colors.dark, ...
    "defaultLegendColor", "w", ...
    "defaultLegendEdgeColor", [0.82, 0.82, 0.82]);
end
